language: php

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.composer/cache/files
        - ${TRAVIS_BUILD_DIR}/travis/extension-cache

php:
    - 7.3
    - 8.0

env:
    - ILLUMINATE_VERSION=^8.0 COVERAGE=true
    - ILLUMINATE_VERSION=^9.0

jobs:
    exclude:
        - php: 7.3
          env: ILLUMINATE_VERSION=^9.0

before_install:
    - cp ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini
    - phpenv config-rm xdebug.ini
    - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update --prefer-dist

install: travis_retry composer install --no-interaction --prefer-dist

before_script: phpenv config-add ~/xdebug.ini

script: vendor/bin/phpunit

after_success: sh -c "if [ ! -z ${COVERAGE+x} ]; then php vendor/bin/php-coveralls; fi"

notifications:
    email: false
